capitals = {
    "Argentina": "Buenos Aires",
    "Australia": "Canberra",
    "Azerbaijan": "Baku",
    "Brazil": "Brasilia",
    "Canada": "Ottawa",
    "Denmark": "Copenhagen",
    "Egypt": "Cairo",
    "France": "Paris",
    "Germany": "Berlin",
    "Iceland": "Reykjavik",
    "India": "New Delhi",
    "Italy": "Rome",
    "Japan": "Tokyo",
    "Kenya": "Nairobi",
    "Lebanon": "Beirut",
    "Morocco": "Rabat",
    "Nepal": "Kathmandu",
    "Portugal": "Lisbon",
    "Romania": "Bucharest",
    "Russia": "Moscow",
    "Scotland": "Edinburgh",
    "Spain": "Madrid",
    "Sweden": "Stockholm",
    "Switzerland": "Bern",
    "Thailand": "Bangkok",
    "Turkey": "Ankara",
    "United Kingdom": "London",
    "United States": "Washington D.C.",
    "Vietnam": "Hanoi",
    "Zimbabwe": "Harare",
}
